# Version for this file.
version: 1

before:
  hooks:
    - go mod tidy
    - go mod download
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - id: hello
    main: .main.go   
    binary: hello               
    goos:
      - linux
    goarch:
      - amd64   
    binary: binary-{{ .Os }}-{{ .Arch }}
