name: SLSA go releaser
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build-image:
     runs-on: ubuntu-latest
     outputs:
      hashes: ${{ steps.publish-artifacts.outputs.hashes }}
      image: ${{ steps.publish-artifacts.outputs.name }}
      digest: ${{ steps.publish-artifacts.outputs.digest }}
     steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
              fetch-depth: 0      
      - name: Publish Artifacts
        id : publish-artifacts
        uses: ./.github/actions/publish-image
        with:
          go-version: 1.21.6
          github_token : ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

